[env]
env = "dev"

[logging]
level = "info"

[server]
addr = "0.0.0.0:9936"

[readonly_db_xianshi]
dsn = "readonly:123456@tcp(localhost:3306)/xianshi"
maxIdle = 3
maxOpen = 50
maxLifetime = 30

[master_db_xianshi]
dsn = "root:123456@tcp(localhost:3306)/xianshi"
maxIdle = 3
maxOpen = 50
maxLifetime = 30

[readonly_db_lemon]
dsn = "readonly:123456@tcp(localhost:3306)/lemon"

[master_db_lemon]
dsn = "root:123456@tcp(localhost:3306)/lemon"

[readonly_db_config]
dsn = "readonly:123456@tcp(localhost:3306)/config"

[redis_cache]
addr = "127.0.0.1:6379"
pw = ""
db = 0

[nsqd_circle]
addr = "127.0.0.1:4150"

[nsqlookupd]
addr = "127.0.0.1:4161"

[nsq_producer_xs_cmd]
topic = "xs.cmd"

[image]
image_domain = "http://xs-image-proxy.partying.sg/"
image_proxy_domain = "http://xs-image-proxy.partying.sg/"
